val template = """
{
   "SurveyEntry":{
      "SurveyID":"SV_8qyG8wDdczfQ9y5",
      "SurveyName":"Method Rename Survey v1",
      "SurveyDescription":null,
      "SurveyOwnerID":"UR_02izUEzZbIoFAgZ",
      "SurveyBrandID":"delaware",
      "DivisionID":null,
      "SurveyLanguage":"EN",
      "SurveyActiveResponseSet":"RS_3QJckACtIv0Hn93",
      "SurveyStatus":"Inactive",
      "SurveyStartDate":"0000-00-00 00:00:00",
      "SurveyExpirationDate":"0000-00-00 00:00:00",
      "SurveyCreationDate":"2019-11-21 09:25:57",
      "CreatorID":"UR_02izUEzZbIoFAgZ",
      "LastModified":"2019-11-22 08:49:34",
      "LastAccessed":"0000-00-00 00:00:00",
      "LastActivated":"0000-00-00 00:00:00",
      "Deleted":null
   },
   "SurveyElements":[
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"BL",
         "PrimaryAttribute":"Survey Blocks",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":[
            {
               "Type":"Default",
               "Description":"Test Block",
               "ID":"BL_6sPQTxTc1IRtCBv",
               "BlockElements":[
                  {
                     "Type":"Question",
                     "QuestionID":"QID1"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID2"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID3"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID4"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID5"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID6"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID7"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID8"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID9"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID10"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID11"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID12"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID13"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID14"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID15"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID16"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID17"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID18"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID19"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID20"
                  },
                  {
                     "Type":"Question",
                     "QuestionID":"QID21"
                  }
               ],
               "Options":{
                  "BlockLocking":"false",
                  "RandomizeQuestions":"Advanced",
                  "Randomization":{
                     "Advanced":{
                        "FixedOrder":[
                           "{~SubSet~}",
                           "{~SubSet~}",
                           "{~SubSet~}",
                           "{~SubSet~}",
                           "{~SubSet~}"
                        ],
                        "RandomizeAll":[

                        ],
                        "RandomSubSet":[
                           "QID17",
                           "QID18",
                           "QID19",
                           "QID20",
                           "QID21",
                           "QID1",
                           "QID2",
                           "QID3",
                           "QID4",
                           "QID5",
                           "QID6",
                           "QID7",
                           "QID8",
                           "QID9",
                           "QID10",
                           "QID11",
                           "QID12",
                           "QID13",
                           "QID14",
                           "QID15",
                           "QID16"
                        ],
                        "Undisplayed":[

                        ],
                        "TotalRandSubset":5,
                        "QuestionsPerPage":"1"
                     },
                     "EvenPresentation":true
                  },
                  "BlockVisibility":"Expanded"
               }
            },
            {
               "Type":"Trash",
               "Description":"Trash \/ Unused Questions",
               "ID":"BL_8r0gRVlSqRH8dlX"
            }
         ]
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"FL",
         "PrimaryAttribute":"Survey Flow",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "Type":"Root",
            "FlowID":"FL_1",
            "Flow":[
               {
                  "Type":"Block",
                  "ID":"BL_6sPQTxTc1IRtCBv",
                  "FlowID":"FL_2"
               },
               {
                  "Type":"Block",
                  "FlowID":"FL_6"
               }
            ],
            "Properties":{
               "Count":6,
               "RemovedFieldsets":[

               ]
            }
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SO",
         "PrimaryAttribute":"Survey Options",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "BackButton":"false",
            "SaveAndContinue":"true",
            "SurveyProtection":"PublicSurvey",
            "BallotBoxStuffingPrevention":"false",
            "NoIndex":"Yes",
            "SecureResponseFiles":"true",
            "SurveyExpiration":"None",
            "SurveyTermination":"DefaultMessage",
            "Header":"",
            "Footer":"",
            "ProgressBarDisplay":"None",
            "PartialData":"+1 week",
            "ValidationMessage":"",
            "PreviousButton":" \u2190 ",
            "NextButton":" \u2192 ",
            "SkinLibrary":"delaware",
            "SkinType":"MQ",
            "Skin":"ud1",
            "NewScoring":1,
            "QuestionsPerPage":"1",
            "SurveyName":"Method Rename Survey v1"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID2",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspContext&nbspXXX(final&nbspIdleStrategy&nbspstrategy)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspthis.unifiedNetworkIdleStrategy&nbsp=&nbspstrategy;<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspthis;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q2",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"sharedNetworkIdleStrategy"
               },
               "2":{
                  "Display":"unifiedNetworkIdleStrategy"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID2"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID3",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>private&nbspstatic&nbspvoid&nbspXXX(final&nbspAtomicBuffer&nbspbuffer,&nbspfinal&nbspint&nbsprecordIndex,&nbspfinal&nbspint&nbsplength)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspbuffer.putInt(msgLengthOffset(recordIndex),&nbsplength);<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q3",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"msgLength"
               },
               "2":{
                  "Display":"writeMsgLength"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID3"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID4",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspvoid&nbspXXX(final&nbsplong&nbsplimit)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspstatusMessagesReceivedCount++;<br\/>&nbsp&nbsp&nbsp&nbspsenderLimit&nbsp=&nbsplimit;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q4",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"updatePositionLimitFromStatusMessage"
               },
               "2":{
                  "Display":"senderPositionLimit"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID4"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID5",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>@Override<br\/>public&nbspvoid&nbspXXX(String&nbspjobId)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspMap<String,&nbspObject>&nbspparams&nbsp=&nbspnew&nbspHashMap<String,&nbspObject>(2);<br\/>&nbsp&nbsp&nbsp&nbspparams.put(id,&nbspjobId);<br\/>&nbsp&nbsp&nbsp&nbspgetDbSqlSession().update(unacquireJob,&nbspparams);<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q5",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"unacquireJob"
               },
               "2":{
                  "Display":"resetExpiredJob"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID5"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID6",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspvoid&nbspXXX(final&nbspint&nbspmsgTypeId,&nbspfinal&nbspString&nbspchannel,&nbspfinal&nbspint&nbspstreamId,&nbspfinal&nbspint&nbspsessionId,&nbspfinal&nbspint&nbsptermId,&nbspfinal&nbsplong&nbspinitialPosition,&nbspfinal&nbspTermBuffers&nbsptermBuffers,&nbspfinal&nbsplong&nbspcorrelationId,&nbspfinal&nbspint&nbsppositionCounterId)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsplogBuffersMessage.wrap(tmpBuffer,&nbsp0);<br\/>&nbsp&nbsp&nbsp&nbsplogBuffersMessage.sessionId(sessionId).streamId(streamId).initialPosition(initialPosition).correlationId(correlationId).termId(termId).positionCounterId(positionCounterId);<br\/>&nbsp&nbsp&nbsp&nbsptermBuffers.appendBufferLocationsTo(logBuffersMessage);<br\/>&nbsp&nbsp&nbsp&nbsplogBuffersMessage.channel(channel);<br\/>&nbsp&nbsp&nbsp&nbspfinal&nbspEventCode&nbspeventCode&nbsp=&nbspmsgTypeId&nbsp==&nbspON_NEW_PUBLICATION&nbsp?&nbspEventCode.CMD_OUT_NEW_PUBLICATION_BUFFER_NOTIFICATION&nbsp&nbspEventCode.CMD_OUT_NEW_SUBSCRIPTION_BUFFER_NOTIFICATION;<br\/>&nbsp&nbsp&nbsp&nbsplogger.log(eventCode,&nbsptmpBuffer,&nbsp0,&nbsplogBuffersMessage.length());<br\/>&nbsp&nbsp&nbsp&nbsptransmitter.transmit(msgTypeId,&nbsptmpBuffer,&nbsp0,&nbsplogBuffersMessage.length());<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q6",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"onNewTermBuffers"
               },
               "2":{
                  "Display":"onPublicationReady"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID6"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID7",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>\/**<br\/>&nbsp*&nbspReturn&nbspthe&nbspread&nbspoffset&nbsp*&nbsp*&nbsp@return&nbspoffset<br\/>&nbsp*\/<br\/>public&nbspint&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspoffset;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q7",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"fragmentsRead"
               },
               "2":{
                  "Display":"offset"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID7"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID8",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>private&nbspvoid&nbspXXX(final&nbspint&nbspactiveTermId)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspsetupHeader.sessionId(sessionId).streamId(streamId).initialTermId(initialTermId).activeTermId(activeTermId).termOffset(0).termLength(termLength).mtuLength(mtuLength).frameLength(SetupFlyweight.HEADER_LENGTH).headerType(HeaderFlyweight.HDR_TYPE_SETUP).flags((byte)&nbsp0).version(HeaderFlyweight.CURRENT_VERSION);<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q8",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"initSetupFrame"
               },
               "2":{
                  "Display":"constructSetupFrame"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID8"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID9",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspint&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspjdbcMaxIdleTimeExcessConnections;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q9",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"getJdbcMaxIdleTimeExcessConnections"
               },
               "2":{
                  "Display":"getJdbcMaxActiveConnections"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID9"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID10",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>\/**<br\/>&nbsp*&nbsp*&nbspGet&nbspthe&nbsplength&nbspof&nbspa&nbspframe&nbspfrom&nbspthe&nbspheader.&nbsp*&nbsp*&nbsp@param&nbsplogBuffer&nbspcontaining&nbspthe&nbspframe.<br\/>&nbsp*&nbsp*&nbsp@param&nbspframeOffset&nbspat&nbspwhich&nbspa&nbspframe&nbspbegins.&nbsp*&nbsp@return&nbspthe&nbspvalue&nbspfor&nbspthe&nbspframe&nbsplength.<br\/>&nbsp*\/<br\/>public&nbspstatic&nbspint&nbspXXX(final&nbspAtomicBuffer&nbsplogBuffer,&nbspfinal&nbspint&nbspframeOffset)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspint&nbspframeLength&nbsp=&nbsplogBuffer.getIntVolatile(lengthOffset(frameOffset));<br\/>&nbsp&nbsp&nbsp&nbspif&nbsp(ByteOrder.nativeOrder()&nbsp!=&nbspByteOrder.LITTLE_ENDIAN)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspframeLength&nbsp=&nbspInteger.reverseBytes(frameLength);<br\/>&nbsp&nbsp&nbsp&nbsp}<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspframeLength;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q10",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"frameLengthVolatile"
               },
               "2":{
                  "Display":"frameLength"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID10"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID11",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspint&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbsplimit.counterId();<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q11",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"limitCounterId"
               },
               "2":{
                  "Display":"upperBoundCounterId"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID11"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID12",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspDmnEngineConfiguration&nbspXXX(int&nbspjdbcMaxIdleTime)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspthis.jdbcMaxIdleTime&nbsp=&nbspjdbcMaxIdleTime;<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspthis;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q12",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"setJdbcMaxIdleTime"
               },
               "2":{
                  "Display":"setJdbcMaxIdleConnections"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID12"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID13",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>private&nbspstatic&nbspint&nbspXXX(final&nbspAeronUri&nbspaeronUri,&nbspfinal&nbspint&nbspdefaultTermLength)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspfinal&nbspString&nbsptermLengthParam&nbsp=&nbspaeronUri.get(CommonContext.TERM_LENGTH_PARAM_NAME);<br\/>&nbsp&nbsp&nbsp&nbspint&nbsptermLength&nbsp=&nbspdefaultTermLength;<br\/>&nbsp&nbsp&nbsp&nbspif&nbsp(null&nbsp!=&nbsptermLengthParam)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsptermLength&nbsp=&nbspInteger.parseInt(termLengthParam);<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspConfiguration.validateTermBufferLength(termLength);<br\/>&nbsp&nbsp&nbsp&nbsp}<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbsptermLength;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q13",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"getPublicationTermLength"
               },
               "2":{
                  "Display":"getTermBufferLength"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID13"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID14",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>\/**<br\/>&nbsp*&nbsp*&nbspSet&nbspthe&nbspcounter&nbspfor&nbspthe&nbspcontrol&nbsptoggle&nbspfor&nbsptriggering&nbspactions&nbspon&nbspthe&nbspcluster&nbspnode.&nbsp*&nbsp*&nbsp@param<br\/>&nbsp*&nbspcontrolToggle&nbspthe&nbspcounter&nbspfor&nbsptriggering&nbspcluster&nbspnode&nbspactions.&nbsp*&nbsp@return&nbspthis&nbspfor&nbspa&nbspfluent&nbspAPI.<br\/>&nbsp*&nbsp*&nbsp@see&nbspClusterControl<br\/>&nbsp*\/<br\/>public&nbspContext&nbspXXX(final&nbspCounter&nbspcontrolToggle)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspthis.controlToggle&nbsp=&nbspcontrolToggle;<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspthis;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q14",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"controlToggle"
               },
               "2":{
                  "Display":"controlToggleCounter"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID14"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID15",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspConsumer<Throwable>&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspeventLoggerlogException;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q15",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"errorHandler"
               },
               "2":{
                  "Display":"exceptionConsumer"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID15"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID16",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>private&nbspint&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspwhile&nbsp(true)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspfinal&nbspint&nbspsessionId&nbsp=&nbspnextSessionId++;<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspif&nbsp(activeSessionIds.add(sessionId))&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspreturn&nbspsessionId;<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp}<br\/>&nbsp&nbsp&nbsp&nbsp}<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q16",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"assignSessionId"
               },
               "2":{
                  "Display":"nextAvailableSessionId"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID16"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID17",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>@Override<br\/>public&nbspString&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbspid;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q17",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"getSequenceFlowId"
               },
               "2":{
                  "Display":"getId"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID17"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID18",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>private&nbsplong&nbspXXX(final&nbspint&nbspsessionId)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspfinal&nbspCountersReader&nbspcounters&nbsp=&nbspaeron.countersReader();<br\/>&nbsp&nbsp&nbsp&nbspidleStrategy.reset();<br\/>&nbsp&nbsp&nbsp&nbspint&nbsprecordingCounterId&nbsp=&nbspRecordingPos.findCounterIdBySession(counters,&nbspsessionId);<br\/>&nbsp&nbsp&nbsp&nbspwhile&nbsp(CountersReader.NULL_COUNTER_ID&nbsp==&nbsprecordingCounterId)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspcheckInterruptedStatus();<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspidleStrategy.idle();<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsprecordingCounterId&nbsp=&nbspRecordingPos.findCounterIdBySession(counters,&nbspsessionId);<br\/>&nbsp&nbsp&nbsp&nbsp}<br\/>&nbsp&nbsp&nbsp&nbspfinal&nbsplong&nbsprecordingId&nbsp=&nbspRecordingPos.getRecordingId(counters,&nbsprecordingCounterId);<br\/>&nbsp&nbsp&nbsp&nbsplogRecordingPosition&nbsp=&nbspnew&nbspReadableCounter(counters,&nbsprecordingCounterId);<br\/>&nbsp&nbsp&nbsp&nbspquorumPosition&nbsp=&nbspQuorumPos.allocate(aeron,&nbsptempBuffer,&nbsprecordingId,&nbspleadershipTermBeginPosition,&nbspleadershipTermId,&nbspsessionId,&nbsp-1);<br\/>&nbsp&nbsp&nbsp&nbspreturn&nbsprecordingId;<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q18",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"findLogRecording"
               },
               "2":{
                  "Display":"setupLogRecordingTracking"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID18"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID19",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>public&nbspvoid&nbspXXX(final&nbspString&nbspchannel,&nbspfinal&nbspint&nbspstreamId,&nbspfinal&nbspint&nbspsessionId,&nbspfinal&nbsplong&nbspposition,&nbspfinal&nbspString&nbspsourceIdentity)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspif&nbsp(channel.equals(pongChannel)&nbsp&&&nbsppongStreamId&nbsp==&nbspstreamId)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspconnectionLatch.countDown();<br\/>&nbsp&nbsp&nbsp&nbsp}<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q19",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"onNewConnection"
               },
               "2":{
                  "Display":"onNewImage"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID19"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID20",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br\/><br\/><code>private&nbspvoid&nbspXXX()&nbsp{<br\/>&nbsp&nbsp&nbsp&nbspfinal&nbspRecordingIndex.Entry&nbspsnapshot&nbsp=&nbspctx.recordingIndex().getLatestSnapshot();<br\/>&nbsp&nbsp&nbsp&nbspif&nbsp(null&nbsp!=&nbspsnapshot)&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspcachedEpochClock.update(snapshot.timestamp);<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspleadershipTermBeginPosition&nbsp=&nbspsnapshot.logPosition;<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspmessageIndex.setOrdered(snapshot.messageIndex);<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsptry&nbsp(Counter&nbspignore&nbsp=&nbspSnapshotPos.allocate(aeron,&nbsptempBuffer,&nbspsnapshot.logPosition,&nbspsnapshot.messageIndex,&nbspsnapshot.timestamp))&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsploadSnapshot(snapshot.recordingId);<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspwaitForState(ConsensusModule.State.REPLAY,&nbspctx.idleStrategy());<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp}<br\/>&nbsp&nbsp&nbsp&nbsp}&nbspelse&nbsp{<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspfinal&nbspCounter&nbspcounter&nbsp=&nbspSnapshotPos.allocate(aeron,&nbsptempBuffer,&nbsp0,&nbsp0,&nbsp0);<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspwaitForState(ConsensusModule.State.REPLAY,&nbspctx.idleStrategy());<br\/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspcounter.close();<br\/>&nbsp&nbsp&nbsp&nbsp}<br\/>}<\/code><br\/><br\/>",
            "DataExportTag":"Q20",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Choices":{
               "1":{
                  "Display":"recoverFromSnapshot"
               },
               "2":{
                  "Display":"checkForSnapshot"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID20"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID21",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"What was your general strategy for choosing which name to select?",
            "DefaultChoices":false,
            "DataExportTag":"Q21",
            "QuestionType":"TE",
            "Selector":"SL",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":null,
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "GradingData":[

            ],
            "Language":[

            ],
            "NextChoiceId":4,
            "NextAnswerId":1,
            "SearchSource":{
               "AllowFreeResponse":"true"
            },
            "QuestionID":"QID21"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SCO",
         "PrimaryAttribute":"Scoring",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "ScoringCategories":[

            ],
            "ScoringCategoryGroups":[

            ],
            "ScoringSummaryCategory":null,
            "ScoringSummaryAfterQuestions":0,
            "ScoringSummaryAfterSurvey":0,
            "DefaultScoringCategory":null,
            "AutoScoringCategory":null
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"PROJ",
         "PrimaryAttribute":"CORE",
         "SecondaryAttribute":null,
         "TertiaryAttribute":"1.1.0",
         "Payload":{
            "ProjectCategory":"CORE",
            "SchemaVersion":"1.1.0"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"STAT",
         "PrimaryAttribute":"Survey Statistics",
         "SecondaryAttribute":null,
         "TertiaryAttribute":null,
         "Payload":{
            "MobileCompatible":true,
            "ID":"Survey Statistics"
         }
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"QC",
         "PrimaryAttribute":"Survey Question Count",
         "SecondaryAttribute":"21",
         "TertiaryAttribute":null,
         "Payload":null
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"RS",
         "PrimaryAttribute":"RS_3QJckACtIv0Hn93",
         "SecondaryAttribute":"Default Response Set",
         "TertiaryAttribute":null,
         "Payload":null
      },
      {
         "SurveyID":"SV_8qyG8wDdczfQ9y5",
         "Element":"SQ",
         "PrimaryAttribute":"QID1",
         "SecondaryAttribute":"Which name would you choose for the following test:\/** \u00a0*\u00a0*\u00a0Find\u00a0the\u00a0active\u00a0counter\u00a0id\u00a0for\u00a0",
         "TertiaryAttribute":null,
         "Payload":{
            "QuestionText":"Which name would you choose for the following test:<br><br><code>\/**<br>&nbsp;*&nbsp;*&nbsp;Find&nbsp;the&nbsp;active&nbsp;counter&nbsp;id&nbsp;for&nbsp;a&nbsp;stream&nbsp;based&nbsp;on&nbsp;the&nbsp;recording&nbsp;id.&nbsp;*&nbsp;*&nbsp;@param&nbsp;countersReader<br>&nbsp;*&nbsp;to&nbsp;search&nbsp;within.&nbsp;*&nbsp;@param&nbsp;recordingId&nbsp;for&nbsp;the&nbsp;active&nbsp;recording.&nbsp;*&nbsp;@return&nbsp;the&nbsp;counter&nbsp;id&nbsp;if<br>&nbsp;*&nbsp;found&nbsp;otherwise&nbsp;{@link&nbsp;#NULL_COUNTER_ID}.<br>&nbsp;*\/<br>public&nbsp;static&nbsp;int&nbsp;XXX(final&nbsp;CountersReader&nbsp;countersReader,&nbsp;final&nbsp;long&nbsp;recordingId)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;final&nbsp;DirectBuffer&nbsp;buffer&nbsp;=&nbsp;countersReader.metaDataBuffer();<br>&nbsp;&nbsp;&nbsp;&nbsp;for&nbsp;(int&nbsp;i&nbsp;=&nbsp;0,&nbsp;size&nbsp;=&nbsp;countersReader.maxCounterId();&nbsp;i&nbsp;&lt;&nbsp;size;&nbsp;i++)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(countersReader.getCounterState(i)&nbsp;==&nbsp;RECORD_ALLOCATED)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;final&nbsp;int&nbsp;recordOffset&nbsp;=&nbsp;CountersReader.metaDataOffset(i);<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(buffer.getInt(recordOffset&nbsp;+&nbsp;TYPE_ID_OFFSET)&nbsp;==&nbsp;RECORDING_POSITION_TYPE_ID&nbsp;&amp;&amp;&nbsp;buffer.getLong(recordOffset&nbsp;+&nbsp;KEY_OFFSET&nbsp;+&nbsp;RECORDING_ID_OFFSET)&nbsp;==&nbsp;recordingId)&nbsp;{<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;i;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;}<br>&nbsp;&nbsp;&nbsp;&nbsp;return&nbsp;NULL_COUNTER_ID;<br>}<\/code><br>",
            "DataExportTag":"Q1",
            "QuestionType":"MC",
            "Selector":"SAVR",
            "SubSelector":"TX",
            "Configuration":{
               "QuestionDescriptionOption":"UseText"
            },
            "QuestionDescription":"Which name would you choose for the following test:\/** \u00a0*\u00a0*\u00a0Find\u00a0the\u00a0active\u00a0counter\u00a0id\u00a0for\u00a0a\u00a0stre...",
            "Choices":{
               "1":{
                  "Display":"findActiveRecordingCounterId"
               },
               "2":{
                  "Display":"findActiveCounterIdByRecording"
               }
            },
            "ChoiceOrder":[
               "1",
               "2"
            ],
            "Validation":{
               "Settings":{
                  "ForceResponse":"OFF",
                  "ForceResponseType":"ON",
                  "Type":"None"
               }
            },
            "Language":[

            ],
            "NextChoiceId":3,
            "NextAnswerId":1,
            "QuestionID":"QID1",
            "DataVisibility":{
               "Private":false,
               "Hidden":false
            }
         }
      }
   ]
}
"""